server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.cyh.spring.cloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root

eureka:
  client:  #客户端注册进Eureka服务列表
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: microservicecloud-dept-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: cyh-microservicecloud-8001
  company.name: www.cyh.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$